#!/bin/bash

tput init
# allows CTRL c to exit
trap "exit" INT TERM
[[ $EUID != 0 ]] && exec sudo "$0" "$@"
#
# Get the script directory
script_dir="$(dirname "$0")"

[[ -d "$script_dir/../tools" ]] && tools_dir="$script_dir/../tools"
[[ ! -d "$script_dir/../lib" && -n "$tools_dir" ]] && echo -e "Please run\nbash "$tools_dir/config-assemble.sh" to build the lib directory\n" && exit 1 


# Define the lib directory one level up from the script directory
lib_dir="$script_dir/../lib/armbian-config"
doc_dir="$script_dir/../share/doc/armbian-config"
json_file="$lib_dir/config.jobs.json"

# Prepare the module options array
declare -A module_options

#
# Load configng core functions and module options array

source "$lib_dir/config.functions.sh"
set_interface
set_runtime_variables
check_distro_status

echo "Loaded Runtime variables..." #| show_infobox ;
echo "Loaded Dialog..." #| show_infobox ;
source "$lib_dir/config.docs.sh"
echo "Loaded Docs..." #| show_infobox ;
source "$lib_dir/config.system.sh"
echo "Loaded System helpers..." #| show_infobox ;
source "$lib_dir/config.network.sh"
echo "Loaded Network helpers..." #| show_infobox ;
source "$lib_dir/config.software.sh"
echo "Loaded Software helpers..." #| show_infobox ;
#
# Loads the variables from beta armbian-config for runtime handling
#json_data=$(generate_json_data)
json_data=$(generate_module_list)

source "$lib_dir/config.runtime.sh"
echo "Loaded Runtime conditions..." #| show_infobox ;

clear

case "$1" in
"--help")
	if [[ -n "$2" ]]; then
		see_cmd_list "$2"
		echo ""
		exit 0
	fi

	echo "Usage:  armbian-config --[option]
     Options:
     --help [category]   Use [category] to filter specific menu options.
     --cmd  [option]     Run a command from the menu (simple)
     --api  [option]     Run a helper command        (advanced)
     --doc               Generate the README.md file 

     Examples:
     armbian-config --help [cmd||System||Software||Network||Localisation]
     armbian-config --cmd help 
     armbian-config --api help
"
	exit 0
	;;
"--doc")
	generate_readme
	exit 0
	;;
"--cmd")
	INPUTMODE="cmd"
	shift
	if [[ -z "$1" || "$1" == "help" ]]; then
		see_cmd_list
		exit 0
	fi
	args=$(sanitize_input "$@")
	execute_command "$args"
	exit 0
	;;
"--api")
	shift
	if [[ -z "$1" || "$1" == "help" ]]; then
		see_use
		exit 0
	fi
	option="$1"
	shift
	args="$@"
	# echo -e "\"$option\" \"$args\""
	"$option" "$args"
	exit 0
	;;
"--noint")
	shift
	if [[ -z "$1" || "$1" == "help" ]]; then
		see_use
		exit 0
	fi
	option="$1"
	shift
	args="$@"
	"$option" "$args"
	exit 0
	;;
*)
	if [[ $EUID != 0 ]]; then
		echo -e "error: Exiting \nTry: 'sudo armbian-config'\n or: 'armbian-config --help' for More info\n\n"
		exit 0
	fi
	;;
esac


#
# Generate the top menu with the modified Object data
set_colors 4
generate_top_menu "$json_data"

#
# Exit the script with a success status code

#
# Show about this tool on exit
about_armbian_configng

exit 0
