#!/bin/sh
# prerm script for mypackage

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Function to remove the package.
remove_mypackage() {
    echo "Removing"
}

# Actions to perform based on script arguments.
case "$1" in
    remove)
        remove_mypackage
        ;;
esac

#DEBHELPER#

exit 0
