#!/bin/sh
# postinst script for mypackage

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Function to configure the package.
configure_mypackage() {
    echo "Ready"
}

# Actions to perform based on script arguments.
case "$1" in
    configure)
        configure_mypackage
        ;;
esac

#DEBHELPER#

exit 0
